# -*- coding: utf-8 -*-
"""BERT_SpamDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpgJEzRiaGh3dfFaX2Dlx4tqkpYs6-dn

# Load libraries
"""

!pip install tensorflow-text

import tensorflow as tf
import tensorflow_hub as hub
import pandas as pd
import tensorflow_text as text
import tf_keras
from sklearn.preprocessing import OneHotEncoder
import numpy as np

"""# Load & Preprocess Dataset"""

df = pd.read_csv("/content/spam.csv", encoding="latin-1")
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
df.head()

df.rename(columns = {'v1':'Category', 'v2':'Message'}, inplace = True)
df.head()

# df.groupby('Category').describe()

encoder = OneHotEncoder(sparse_output=False)
encoded_array = encoder.fit_transform(df[['Category']])

one_hot_encoded_df_sklearn = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(['Category']))

df = pd.concat([df,one_hot_encoded_df_sklearn], axis=1)
df.head()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Message'],one_hot_encoded_df_sklearn)

X_train.head()

y_train.head()

"""# Importing Keras Layers"""

bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

"""# Model Creation"""

# def get_sentence_embeding(sentences):
#     preprocessed_text = bert_preprocess(sentences)
#     return bert_encoder(preprocessed_text)['pooled_output']

"""## Input layer"""

text_input = tf_keras.layers.Input(shape=(), dtype=tf.string, name='text')

"""## Bert layers"""

preprocessed_text = bert_preprocess(text_input)

outputs = bert_encoder(preprocessed_text)

"""## Neural network layers"""

l = tf_keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf_keras.layers.Dense(2, activation='softmax', name="output")(l)

"""# Construct final model"""

model = tf_keras.Model(inputs=[text_input], outputs = [l])

model.summary()

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'],
              run_eagerly=True)

"""# Training & Evaluation"""

model.fit(X_train, y_train, epochs=2, batch_size=32)

model.evaluate(X_test, y_test)

#predict
y_predicted = model.predict(X_test)
# y_predicted = y_predicted.flatten()
print(y_predicted)

# y_predicted = np.where(y_predicted > 0.5, 1, 0)
# y_predicted

from sklearn.metrics import accuracy_score, f1_score, classification_report

# Convert one-hot encoded targets and probability predictions to class indices (0 for ham, 1 for spam)
y_test_labels = np.argmax(y_test.values, axis=1)
y_pred_labels = np.argmax(y_predicted, axis=1)

print(f"Accuracy Score: {accuracy_score(y_test_labels, y_pred_labels)}")

f1_score(y_test_labels,y_pred_labels)

print(classification_report(y_test_labels,y_pred_labels))

model.save('spam_bert_model.h5')

